services:
  - type: web
    name: mini-saas
    env: php
    region: singapore
    buildCommand: "./render-build.sh"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase: mini-saas-db
        property: host
      - key: DB_PORT
        fromDatabase: mini-saas-db
        property: port
      - key: DB_DATABASE
        fromDatabase: mini-saas-db
        property: database
      - key: DB_USERNAME
        fromDatabase: mini-saas-db
        property: user
      - key: DB_PASSWORD
        fromDatabase: mini-saas-db
        property: password

databases:
  - name: mini-saas-db
    plan: free
    region: singapore
